post http://localhost:3003/api/stockData
Content-Type: application/json

{
   "code":"AAPL",
   "quotes":[
      {
         "date":"01/20/2021",
         "closelast":"132.03",
         "volume":"104319500",
         "open":"128.66",
         "high":"132.49",
         "low":"128.55"
      },
      {
         "date":"01/19/2021",
         "closelast":"127.83",
         "volume":"90757330",
         "open":"127.78",
         "high":"128.71",
         "low":"126.938"
      },
      {
         "date":"01/15/2021",
         "closelast":"127.14",
         "volume":"111598500",
         "open":"128.78",
         "high":"130.2242",
         "low":"127"
      },
      {
         "date":"01/14/2021",
         "closelast":"128.91",
         "volume":"90221760",
         "open":"130.8",
         "high":"131",
         "low":"128.76"
      }
   ]
}